name: Technically Creative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.61408
title: Technically Creative
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#70614c'
    - '#54a5f6'
    - '#1545d0'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
