title: Technically Creative
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.875
  lightness: 0.875
  brandStrength: 1
  brandColors:
    - '#ffffff'
    - '#4f4f4f'
    - '#9f9f9f'
    - '#cfcfcf'
    - '#676767'
  rhythmicContrast: 0.5067453
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Technically Creative
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.61408
layout_spectrum: 1
