name: Technically Creative
favicon: null
layout_spectrum: 1
typography_spectrum: 0.74746
title: Technically Creative
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#70614c'
    - '#54a5f6'
    - '#1545d0'
  brandStrength: 0.75
  lightness: 1
  saturation: 0
  rhythmicContrast: 1
purpose: []
