name: Technically Creative
favicon: null
layout_spectrum: 0.00763
typography_spectrum: 0.74746
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#131112'
    - '#c2c3d8'
    - '#8586a2'
    - '#3c3a4f'
  brandStrength: 0.5
  lightness: 0
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
